### ISSUE TITLE
Broken example in documentation

### ISSUE THREAD

**Issue by steve-biggs-fox** [StephenSmith25/PythonFMU3#5]
The docs are here: https://pythonfmu3.readthedocs.io/en/latest/usage/

Examples are given.

The second one, BouncingBall, does not compile, with the error message: AttributeError: 'BouncingBall' object has no attribute 'ball'

**Comment by StephenSmith25** [comment]
Hey, thanks for finding that. Sorry, I rushed the documentation together and haven't looked at it since. Looks like it's just missing a 'nested=False' for the variable 'derh'.

**Comment by StephenSmith25** [comment]
Fixed
