### ISSUE TITLE
Model description does not end up in the FMU

### ISSUE THREAD

**Issue by steve-biggs-fox** [StephenSmith25/PythonFMU3#7]
Documentation shows that the model description should be specified like this:

```
class PythonSlave(Fmi3Slave):

    author = "John Doe"
    description = "A simple description"
    ...
```

However, if I then run `fmpy.dump(...)` on the resultant FMU, it displays the following:

```
Model Info

  FMI Version        3.0
  FMI Type           Co-Simulation
  Model Name         PythonSlave
  Description        None
  ...
```

By contrast, if I run `fmpy.dump(...)` on an FMU generated by another program, then I get, for example:

```
Model Info

  FMI Version        2.0
  FMI Type           Co-Simulation
  Model Name         160424_V9LCSUT
  Description        Simcenter Flomaster network with FMI for co-simulation interface
  ...
```

i.e. the problem is not with `fmpy.dump(...)`.

**Comment by StephenSmith25** [comment]
I'll have to look at this as I have not come across it, thanks for raising it!

**Comment by StephenSmith25** [comment]
Fixed. Indicated that the description should appear in `__init__` rather than as a class attribute.
